### Spam Detection Using Machine Learning
+ Build ML Models
+ Use our ML Model as a package

In [2]:
# Load EDA Pkgs
import pandas as pd 
import numpy as np

In [3]:
# Load ML Pkgs
# ML Packages For Vectorization of Text For Feature Extraction
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

In [5]:
# Visualization Packages
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
# Load Dataset
df = pd.read_csv("data/spamdataset.csv")

In [7]:
df.head()

Unnamed: 0  Unnamed: 1                                   COMMENT_ID  \
0        Psy           0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
1        Psy           1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
2        Psy           2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
3        Psy           3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
4        Psy           4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   

             AUTHOR                 DATE  \
0         Julius NM  2013-11-07T06:20:48   
1       adam riyati  2013-11-07T12:37:15   
2  Evgeny Murashkin  2013-11-08T17:34:21   
3   ElNino Melendez  2013-11-09T08:28:43   
4            GsMega  2013-11-10T16:05:38   

                                             CONTENT  CLASS  
0  Huh, anyway check out this you[tube] channel: ...      1  
1  Hey guys check out my new channel and our firs...      1  
2             just for test I have to say murdev.com      1  
3   me shaking my sexy ass on my channel enjoy ^_^       1  
4            watch?v=vtaRGgvGtWQ   Check this out .      1

In [8]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT',
       'CLASS'],
      dtype='object')

In [9]:
df.columns = df.columns.str.lower()

In [10]:
df.columns

Index(['unnamed: 0', 'unnamed: 1', 'comment_id', 'author', 'date', 'content',
       'class'],
      dtype='object')

In [11]:
df[['content','class']].head()

content  class
0  Huh, anyway check out this you[tube] channel: ...      1
1  Hey guys check out my new channel and our firs...      1
2             just for test I have to say murdev.com      1
3   me shaking my sexy ass on my channel enjoy ^_^       1
4            watch?v=vtaRGgvGtWQ   Check this out .      1

In [12]:
df1 = df[['content','class']]

In [13]:
# Extract Feature With CountVectorizer
corpus = df['content']
cv = CountVectorizer()
X = cv.fit_transform(corpus) # Fit the Data

In [14]:
cv.get_feature_names()

['00',
 '000',
 '002',
 '018',
 '02',
 '034',
 '04',
 '047000',
 '05',
 '053012',
 '0687119038',
 '08',
 '09',
 '0cb8qfjaa',
 '0d878a889c',
 '0dbhjzdw0lbsjbi40gxm0d0p5krhv8xinqli53__wqbahs8zx4mjhw5vwrkpxfoeks',
 '0laviqu2b',
 '10',
 '100',
 '1000',
 '10000000',
 '1000000000',
 '100000415527985',
 '100005244783212',
 '100007085325116',
 '10001',
 '100877300245414',
 '101721377578919894134',
 '10200253113705769',
 '1030',
 '104999962146104962510',
 '10626048',
 '10626835',
 '106865403',
 '107297364',
 '1073741825',
 '1073741828',
 '1073741830',
 '1073741943',
 '108k',
 '109',
 '10b35481',
 '11',
 '1111',
 '1111111111111111111',
 '111719098841907',
 '111982027348137311818',
 '112720997191206369631',
 '11cpwb',
 '11th',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '128gb',
 '12year',
 '13',
 '13017194',
 '131275322914',
 '131338190916',
 '1337',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '134

In [40]:
spam_vectorizer_model = open("spam_vectorizer.pkl","wb")
joblib.dump(cv,spam_vectorizer_model)

In [41]:
spam_vectorizer_model.close()

In [15]:
y = df['class']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
print(df.shape)
print(X_train.shape)

(1956, 7)
(1310, 4454)


In [19]:
# Naive Bayes Classifier

nb = MultinomialNB()
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [20]:
# Accuracy Score
nb.score(X_test,y_test)

0.9195046439628483

In [21]:
# Sample Prediciton of A Text if it is a spam
comment = ["Check this out"]
vect = cv.transform(comment).toarray()

In [23]:
#class_dict = {'ham':0,'spam':1}
nb.predict(vect)

array([1])

In [24]:
# Sample Prediciton 2
comment1 = ["Great song Friend"]
vect2 = cv.transform(comment1).toarray()
nb.predict(vect2)


array([0])

In [ ]:
# Save Models

In [26]:
import joblib

In [27]:
spam_detector_nb_model = open("spam_detector_nb_model.pkl","wb")
joblib.dump(nb,spam_detector_nb_model)

In [28]:
spam_detector_nb_model.close()

### Using Logistic Regression

In [29]:
# Logistic Regression
logit = LogisticRegression()
logit.fit(X_train,y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [30]:
logit.score(X_test,y_test)

0.9535603715170279

In [32]:
logit.predict(vect2)

array([0])

In [33]:
spam_detector_logit_model = open("spam_detector_logit_model.pkl","wb")
joblib.dump(logit,spam_detector_logit_model)

In [34]:
spam_detector_logit_model.close()

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [37]:
# Accuracy
rf.score(X_test,y_test)

0.9520123839009288

In [38]:
spam_detector_rf_model = open("spam_detector_rf_model.pkl","wb")
joblib.dump(rf,spam_detector_rf_model)
spam_detector_rf_model.close()

In [39]:
### Thanks For Your Time
### Jesus Saves @JCharisTech
### Jesse E.Agbe (JCharis)